### ISSUE TITLE
NSException on Run

### ISSUE THREAD

**Issue by Entity3Ltd** [tapdaq/unity-plugin#10]
I just download and updated to your latest Unity Plugin release.
I now get the below error where as before everything was running ok.
It build fine but crashes on launch from xCode.

libc++abi.dylib: terminating with uncaught exception of type NSException

this line is highlighted in main.mm

UIApplicationMain(argc, argv, nil, [NSString stringWithUTF8String:AppControllerClassName]);

Thanks

**Comment by nickreffitt** [comment]
Hi @Entity3Ltd - could you confirm you followed the steps in our quickstart section [Build to Xcode](https://github.com/tapdaq/unity-plugin/wiki/Quickstart#exporting-to-xcode)?

Is there a stacktrace or any further information you could provide for us to replicate the issue?

Many thanks for the input, it's very helpful

Nick

**Comment by Entity3Ltd** [comment]
@nickreffitt 

Sorry totally my fault. I forgot to add the Application and Client Key back into the TapDaq settings after updating. Please Close.

**Comment by nickreffitt** [comment]
Hi @Entity3Ltd - no problem at all, thank you for letting us know
