### ISSUE TITLE
Bitcode

### ISSUE THREAD

**Issue by pescode** [tapdaq/unity-plugin#11]
Any chance to have the libs with bitcode enabled?

Frameworks/Plugins/iOS/Tapdaq.framework/Tapdaq(TDConfig.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by nickreffitt** [comment]
Hi @pescode, we're currently working on a fix in our SDK to support bitcode, I'll keep this ticket open and get back to you as soon as we've pushed a fix for it

Let me know if you run into any further issues

Nick

**Comment by PixelEnvision** [comment]
@nickreffitt Great news, I'm also waiting for it...

**Comment by JoeCoo7** [comment]
So do I, thanks!

**Comment by nickreffitt** [comment]
Hey @pescode @PixelEnvision @JoeCoo7 

I'm pleased to say that the latest release of the unity plugin has bitcode support.

You can grab the latest plugin here: https://github.com/tapdaq/unity-plugin/archive/master.zip

Let me know if you have any further issues.

Thanks for your patience all

Nick
