### ISSUE TITLE
TapdaqV1 _orientationChangeNotification!

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#12]
Hello,

This is just a minor issue that I wanted to log for a future fix. I guess this is a leftover from the previous version of the plugin.

As there is no receiver object in Unity (prefab is gone), orientation change during the ad playback logs the following to the Xcode without any crashes: "SendMessage: object TapdaqV1 does not have receiver for function _orientationChangeNotification!"

It's called by TapdaqUnityIOS.m and my current workaround to silence it is commenting out two lines starting with UnitySendMessage("TapdaqV1"

Best regards,
E.

**Comment by nickreffitt** [comment]
Hi @PixelEnvision thanks for the feedback, this is useful to know

We'll let you know when we take a look at the issue and keep you updated on our progress

All the best

Nick

**Comment by nickreffitt** [comment]
Hi @PixelEnvision we have removed this notification from the latest release of the unity plugin, could you check it over to see if you still face this log message?

All the best

Nick
