### ISSUE TITLE
Duplicate AdNetworkDebugViewController

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#13]
Hi,

When following the recent quick-start guide with the latest unity plug-in, following is logged to the Xcode console on the app start-up:

objc[382]: Class AdNetworkDebugViewController is implemented in both /var/containers/Bundle/Application/B0B4304B-1286-465E-A69A-6B16E7C991B3/kubic.app/kubic (0x101408fa0) and /var/containers/Bundle/Application/B0B4304B-1286-465E-A69A-6B16E7C991B3/kubic.app/kubic (0x101408fa0). One of the two will be used. Which one is undefined.

Removing AdNetworkDebugViewController.m from the Compile Sources section seems to silence it without any side effects.

Best regards,
E.

**Comment by agarwalmukund** [comment]
Hi @PixelEnvision 

Thank you for that. 
We are working on streamlining the Unity iOS steps which should resolve this logging message.

Kind regards,
Mukund

**Comment by nickreffitt** [comment]
@PixelEnvision could you drop me an email on nick@tapdaq.com if that's possible? 

Thanks
Nick

**Comment by PixelEnvision** [comment]
@nickreffitt Of course, sent...
