### ISSUE TITLE
Hide Banners

### ISSUE THREAD

**Issue by pescode** [tapdaq/unity-plugin#14]
Is there a way to hide or destroy a banner?

**Comment by agarwalmukund** [comment]
Hi @pescode 

Unfortunately, not yet in the Unity plugin.
We have asked our Unity team for this feature and also to provide more control to the developer.

Thank you,
Mukund

**Comment by JoeCoo7** [comment]
Any ETA on that feature? Thank for you hard work! :)

**Comment by nickreffitt** [comment]
Hey @pescode @JoeCoo7 apologies about the delay here, we're working through several issues at the moment, but I will keep you posted once we have a fix out. I'll provide an ETA as soon as I can 

Apologies for the inconvenience

Nick

**Comment by nickreffitt** [comment]
Hi @pescode @JoeCoo7 apologies for the delay here, but I am pleased to say we have now resolved this issue for you, there is now a call to hide a banner

```AdManager.HideBanner();```

You can see the updated documentation regarding banners here: https://tapdaq.com/docs/unity-plugin/Banner

Let me know if there's anything else we can help with.

All the best 

Nick
