### ISSUE TITLE
INTERSTITIAL: FAILED_TO_DISPLAY

### ISSUE THREAD

**Issue by nekenPL** [tapdaq/unity-plugin#15]
HI,

On iOS i try to display Interstitial ad. Unfortunately i got this error:

2016-12-12 21:58:10.371 theoffice[473:56250] [TapdaqUnityiOS] showInterstitial called
2016-12-12 21:58:10.371 theoffice[473:56250] [Tapdaq SDK] INFO: You haven’t set a placement tag for this interstitial yet. Why don’t you use showInterstitialForPlacementTag:?
-- Test Log -- INTERSTITIAL: FAILED_TO_DISPLAY
Tapdaq.TDCallbacks:OnAdError(TDAdEvent)

I don't use a tag for interstitial i call this method to display:

  Tapdaq.AdManager.ShowInterstitial();

**Comment by nekenPL** [comment]
@nickreffitt  can You help? :)

**Comment by nickreffitt** [comment]
Hi @nekenPL apologies for missing this

Have you got a promotion set up on the dashboard? You can see a video on how to do this [here](https://youtu.be/VQPS8wIFh-g?t=187).

Let me know if that helps

Thanks

Nick

**Comment by nekenPL** [comment]
Hi @nickreffitt 

I don't think so. Our publisher manager account on Tapdaq. I need display interstitial every app launch.

**Comment by alastairtapdaq** [comment]
Hi @nekenPL,

I can help with this, I'll set up a promotion for you manually. 

Could you please let me know the email that you signed up with?

Thanks
Ali

**Comment by nekenPL** [comment]
Hi @alastairtapdaq 

Unfortunately i don't know it :) This is my publisher account. He gave me  iOS Application ID and iOS Client Key.

**Comment by alastairtapdaq** [comment]
Hi @nekenPL,

Okay, no worries. What is the name of your Publisher? Any identifier you could give me so I can find the account would be great.

As I will be setting up a promotion to test, please let me know the two apps inside the account that are suitable (perhaps the 2 that are most relevant to you).

Thanks,
Ali

**Comment by nekenPL** [comment]
@alastairtapdaq,

AppId: 
580836700a5d6cd3762f85ff

Name: Next Please

Publisher name:  Appsolute Games

**Comment by Entity3Ltd** [comment]
Hi, I am also trying to display Interstitial ads for Appsolute Games. I can not pull a single Interstitial ad. Also Appsolute Games require an Interstitial on game launch for their cross promotional adverts, I can not get one to display on launch either.

Thanks

**Comment by nickreffitt** [comment]
Hey @Entity3Ltd can you contact me on support@tapdaq.com with your app name, we can review the dashboard settings to make sure it's all set up correctly

**Comment by alastairtapdaq** [comment]
Hey @nekenPL,

Thanks for the info!

Which other app is best to run this quick promotion test? Are you involved with another app inside the Appsolute Games portfolio?

Thanks,
Ali

**Comment by Entity3Ltd** [comment]
@nickreffitt I have sent you an email with the details, Thanks

**Comment by nekenPL** [comment]
Hey @alastairtapdaq,

I have no idea :)

**Comment by nickreffitt** [comment]
Hey @nekenPL and @Entity3Ltd we are just going to contact David about the promotion set up and get some clarification on it, once that's sorted we will circle back to you.

Thanks for your patience

All the best

Nick

**Comment by nekenPL** [comment]
Hey,

Any progress for this?

Best

**Comment by alastairtapdaq** [comment]
Hi @nekenPL,

Apologies in the delay in coming back to you on this.

We have reached out to David, and are waiting for his reply on how to proceed with the promotion set up. We are more than happy to action this ourselves if it speeds up the process for you guys, but just need clarification from David on how he wants the promotion to be set up.

Apologies again, and thanks for your patience on this. I'll keep you updated!

Thanks
Alastair

**Comment by Entity3Ltd** [comment]
Hi, I think David has now set up the promotional ad. Can you let me know how you call these on app launch. Thanks

**Comment by nekenPL** [comment]
Hi @Entity3Ltd 

Unfortunately i have still that problem. I upgraded newest version of the plugin but that not help me.

**Comment by Entity3Ltd** [comment]
@nekenPL 

Hi, If you just want to pull up the promotional ad then strip out this latest version from your unity project completely, David suggest this version of the plugin, which I have managed to get working (with ease) to pull the promotional ad.

https://github.com/tapdaq/unity-plugin/releases/tag/1.0.12

Import that unity asset and only pull in the Tapdaq folder and iOS stuff if your exporting to Xcode.

Follow this old version of the WIKI page

https://github.com/tapdaq/unity-plugin/wiki/Quickstart/51cf2ad7615dc2038f4883b92a690cdcb153d48a

Hope this works for you too, Thanks. Also Thanks to Dave for all his help so far

**Comment by nekenPL** [comment]
@Entity3Ltd  i think latest and previous 2.0.9 Unity plugnin has problem with mediation initlization. When i watched a log today i didn't saw any mediation initialization log like "Charbooster initialization".

**Comment by Entity3Ltd** [comment]
@nekenPL yeah I'm just going to use version 1.0.12 as a temporary solution. Once Tapdaq resolve all the issues and release a working SDK i'll try it.

**Comment by nekenPL** [comment]
@Entity3Ltd  i installed 1.0.12 version. My game launch in Portrait mode. After i launch Interstitial my game go landscape mode (it's not good for game) but nothing is displayed. In log i have this errors:

2016-12-23 15:23:08.717 theoffice[1669:467850] Presenting view controllers on detached view controllers is discouraged <UIViewController: 0x1a01c3e0>.
SendMessage: object TapdaqV1 does not have receiver for function _orientationChangeNotification!
2016-12-23 15:23:09.352 theoffice[1669:467850] Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x1a01c3e0>.

Could You help? :)

**Comment by Entity3Ltd** [comment]
@nekenPL  
Did you completely strip out the previous version? Do that first and export a fresh build to xcode, do not append.

Then import this asset. I'll paste the code below shortly to call an interstitial on start

**Comment by Entity3Ltd** [comment]
@nekenPL - below code will pull up the promotional ad on start with 1.0.12. I haven't cut down then code to the bear essentials but i works. Sometimes the ad doesn't show until you proceed to the next scene, but that's as good as it gets right now.

> using UnityEngine;
using System.Collections;
using UnityEngine.SceneManagement;

public class Menu : MonoBehaviour {


	private bool interstitialShown = false;
	public bool interstitialsAvailable = false;
	private bool nativeAdCreated = false;

	private TapdaqNativeAd nativeAd = new TapdaqNativeAd();
	public GameObject nativeCanvas;

	//Subscribe to the tapdaq events
	void OnEnable()
	{
		Tapdaq.willDisplayInterstitial += MyListenerMethod;
		Tapdaq.didDisplayInterstitial += MyListenerMethod_2;
		Tapdaq.didCloseInterstitial += MyListenerMethod_3;
		Tapdaq.didClickInterstitial += MyListenerMethod_4;
		Tapdaq.didFailToLoadInterstitial += MyListenerMethod_5;
		Tapdaq.hasNoInterstitialsAvailable += MyListenerMethod_6;
		//NOTE - this event will be called everytime an interstitial is cached and ready to be shown. 
		//       which can happen multiple times in a few frames
		Tapdaq.hasInterstitialsAvailableForOrientation += MyListenerMethod_7;


		Tapdaq.didFailToLoadNative += MyListenerMethod_8;
		Tapdaq.hasNoNativeAdvertAvailable += MyListenerMethod_9;
		//NOTE - this event will be called everytime a native is cached and ready to be shown. 
		//       which can happen multiple times in a few frames
		Tapdaq.hasNativeAdvertsAvailableForAdUnit += MyListenerMethod_10;
	}

	//Unsubscribe to the tapdaq events
	void OnDisable()
	{
		Tapdaq.willDisplayInterstitial -= MyListenerMethod;
		Tapdaq.didDisplayInterstitial -= MyListenerMethod_2;
		Tapdaq.didCloseInterstitial -= MyListenerMethod_3;
		Tapdaq.didClickInterstitial -= MyListenerMethod_4;
		Tapdaq.didFailToLoadInterstitial -= MyListenerMethod_5;
		Tapdaq.hasNoInterstitialsAvailable -= MyListenerMethod_6;
		Tapdaq.hasInterstitialsAvailableForOrientation -= MyListenerMethod_7;


		Tapdaq.didFailToLoadNative -= MyListenerMethod_8;
		Tapdaq.hasNoNativeAdvertAvailable -= MyListenerMethod_9;
		Tapdaq.hasNativeAdvertsAvailableForAdUnit -= MyListenerMethod_10;
	}


	void Start(){

		ShowInterstitial();

	}
		
	public void ShowInterstitial()
	{
		Tapdaq.ShowInterstitial();
	}

	public void SendNativeClick()
	{
		print ("Native Ad clicked");
		Tapdaq.SendNativeClick(nativeAd);
	}

	void MyListenerMethod()
	{
		// Example
		Debug.Log("Plugin about to show interstitial");
	}
	void MyListenerMethod_2()
	{
		// Example
		Debug.Log("Plugin has shown an interstitial");
	}
	void MyListenerMethod_3()
	{
		// Example
		Debug.Log("An interstitial was closed");
		//interstitialShown = false;
	}
	void MyListenerMethod_4()
	{
		// Example
		Debug.Log("An interstitial was clicked");
	}
	void MyListenerMethod_5()
	{
		// Example
		Debug.Log("Failed to load interstitials");
	}

	void MyListenerMethod_6()
	{
		// Example
		Debug.Log("Interstitials unavailable");
	}
	void MyListenerMethod_7(string orientation)
	{
		// Example: //Here we use a bool to avoid rapid fire interstitial spam. 'orientation' will either be PORTRAIT or LANDSCAPE
		if(!interstitialShown)
		{
			int orient = int.Parse(orientation);
			Debug.Log(string.Format("An interstitial for {0} orientation is available",(Tapdaq.TDOrientation)orient));
			interstitialShown = true;

			Tapdaq.ShowInterstitial();
			interstitialsAvailable = true;
		}
	}


	//NATIVE Event handling

	void MyListenerMethod_8()
	{
		// Example
		Debug.Log("Failed to load Natives");
	}

	void MyListenerMethod_9()
	{
		// Example
		Debug.Log("Has No Natives Available");
	}

	void MyListenerMethod_10(string adType, string adSize, string orientation) 
	{
		//this example method attempts to fetch and display the first available native ad, regardless of category
		int unit = int.Parse(adType);
		int size = int.Parse(adSize);
		int orient = int.Parse(orientation);

		Debug.Log ("Ad type: "+((Tapdaq.TDNativeAdUnit)unit).ToString());
		Debug.Log ("adsize: "+((Tapdaq.TDNativeAdSize)size).ToString());
		Debug.Log ("orientation: "+((Tapdaq.TDOrientation)orient).ToString());
		if(!nativeAdCreated)
		{


			//fetch a native based on the first available type
			nativeAd = Tapdaq.GetNativeAd((Tapdaq.TDNativeAdUnit)unit, (Tapdaq.TDNativeAdSize)size, (Tapdaq.TDOrientation)orient);

			//if not given sufficient loading time, the native ad can return a null object
			if(nativeAd.creativeImage != null)
			{
				nativeCanvas.SetActive(true);

				//Display the image from the nativeAd to a Canvas Image object
				//image.sprite = Sprite.Create(nativeAd.creativeImage,new Rect(0,0,nativeAd.creativeImage.width,nativeAd.creativeImage.height),new Vector2(0.5f,0.5f));
				Tapdaq.SendNativeImpression(nativeAd);
				nativeAdCreated = true;

			}
		}

	}


}

**Comment by Entity3Ltd** [comment]
@nekenPL 

Dont forget you are following this WIKI link, not the other one

https://github.com/tapdaq/unity-plugin/wiki/Quickstart/51cf2ad7615dc2038f4883b92a690cdcb153d48a

**Comment by nekenPL** [comment]
@Entity3Ltd  thank you! Now corss promo working fine.

**Comment by Entity3Ltd** [comment]
@nekenPL 
Great pleased I could help.

@nickreffitt 
Please let us know when a stable and working update is released 

Thanks

**Comment by nickreffitt** [comment]
Hi @nekenPL @Entity3Ltd with the new release of the unity plugin, we have made huge improvements to our ad serving, could you give the latest release a try and see how you get on?

Here's the download link: https://github.com/tapdaq/unity-plugin/archive/master.zip

Let me know how you get on, please reopen this ticket if you have further issues

All the best

Nick
