### ISSUE TITLE
RewardAd problem

### ISSUE THREAD

**Issue by nekenPL** [tapdaq/unity-plugin#16]
Hi,

I wan't to play reward ad and check if user finished watching it.  

I got proper log:
-- Test Log -- Reward video ad is available.

problem is that i received a this debug info:
2016-12-12 21:57:11.759 theoffice[473:56250] [TapdaqUnityiOS] showRewardedVideo called
-- Test Log -- VIDEO: WILL_DISPLAY
Tapdaq.TDEventHandler:_willDisplayVideo()

-- Test Log -- VIDEO: FAILED_TO_DISPLAY
Tapdaq.TDCallbacks:OnAdError(TDAdEvent)
Tapdaq.TDEventHandler:_didFailToDisplayVideo()

Hmm it's correct that tag of ad is VIEDO? In documentation is REWARD_AD

**Comment by PixelEnvision** [comment]
@nekenPL 

Subscribe to TDCallbacks.AdClosed callback and it should return  "REWARD_AD" for e.adType when the ad is closed & rewarded.

I haven't tried this with the latest build yet but that should get you started till their reply. You may also want to check closed issues section for my question & answers on the same subject.

**Comment by nekenPL** [comment]
Thank you.
