### ISSUE TITLE
2.0.6 few more issues

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#18]
Beside the socket error I've reported separately I've noticed following bugs:

**Ads are not always become available automatically**
- Expected behaviour: When a video ad is finished, new one should be downloaded and trigger OnAdAvailable automatically. This happens some times but not always.
- Current behaviour: When a video ad is finished, it just stays that way. If I trigger AdManager.ShowRewardVideo with the button, nothing happens but that seems to trigger downloading of a new video ad as few moments later OnAdAvailable called and button works at the next attempt.

**OnAdClosed & OnAdClicked behaves differently between Unity Ads & Vungle**
- When a unity ad is finished, if I click the download button it triggers OnAdClicked without calling OnAdClosed. I think that's related to displaying the ad within the app as pop-up screen. So, I put my reward code in OnAdClicked.
- On my next attempt a Vungle ad is played. When I click the download button it triggered both OnAdClicked  & OnAdClosed. And it took me to AppStore app. But when I return to my game it triggered OnAdClosed once more. Due to my change as I noted above that resulted granting of the reward 3 times.

Currently I should be able to do the following workarounds, but I wanted to know if any of those behaviours might change as a bug fix which might break my code if I do that.

- I can place a code in OnAdClicked callback to see if it's a unity ad. That should prevent granting an extra reward to Vungle.(PS, that won't be possible as click only reports VIDEO: CLICKED)
- I can put a time limit to granting rewards so it won't do it unless x amount of seconds passed, that should prevent double OnAdClosed calls.

Best regards,
E.

**Comment by nickreffitt** [comment]
Thanks @PixelEnvision for the incredibly detailed feedback. 

I will get our Unity engineers to take a look at this over the coming days.

All the best

Nick

**Comment by nickreffitt** [comment]
Hi @PixelEnvision 

With the recent major release of our unity plugin, we've been able to iron out these issues that you have identified. 

There is now explicit calls to load an ad for a particular ad unit, an example of this is in the rewarded video docs: https://tapdaq.com/docs/unity-plugin/Rewarded-Video 

I'll make this ticket as close, but please reopen if you have further issues here.

All the best and thank you for your patience.

Nick
