### ISSUE TITLE
Building App with unity for android crash!

### ISSUE THREAD

**Issue by fmelogno** [tapdaq/unity-plugin#2]
E/TAPDAQ: Something went wrong while getting advertisement id!
java.lang.NoClassDefFoundError: com.google.android.gms.ads.identifier.AdvertisingIdClient
at com.tapdaq.sdk.TapdaqHelper.getAdvertisementId(TapdaqHelper.java:165)
at com.tapdaq.sdk.TapdaqInitializerRunnable.run(TapdaqInitializerRunnable.java:35)
at java.lang.Thread.run(Thread.java:841)

**Comment by nickreffitt** [comment]
Thanks for bringing this to our attention @fmelogno, we're going to take a look at this first thing tomorrow, and I'll let you know when a fix is ready

**Comment by rdominic** [comment]
Hi @fmelogno, I've updated the Tapdaq Unity SDK to 1.0.12 with Tapdaq Android SDK 2.5.5 with several bug fixes in (Including improvements to the code stated). Please let me know if you are still experiencing problems with this.

If you are still having problems, please let us know if you are using any other 3rd party plugins which might be causing a conflict.

Thanks again for your feedback,
Dominic
