### ISSUE TITLE
Xcode build error

### ISSUE THREAD

**Issue by st-melnyk** [tapdaq/unity-plugin#20]
I'm trying to build project for IOS and got the following linker error:
 "_OBJC_CLASS_$_ZZArchive", referenced from:
objc-class-ref in Tapdaq(TDMVGRequestManager.o)
ld: symbol(s) not found for architecture arm64

I'm using Unity 5.4.1f, and Xcode Version 8.1 (8B62)
The commit 7757962895a64e0f8e9161ad80bf11e375dccba6 (14 Dec 2016)

**Comment by nickreffitt** [comment]
Hi @st-melnyk 

Thanks for reaching out, it appears you are missing the ZipZap framework from your Xcode build

Could you double-check our guide on [Exporting to Xcode](https://github.com/tapdaq/unity-plugin/wiki/Quickstart#exporting-to-xcode) so they match with your project.

Let me know how you get on

All the best

Nick

**Comment by st-melnyk** [comment]
Thanks, it worked
