### ISSUE TITLE
Close button not available

### ISSUE THREAD

**Issue by pescode** [tapdaq/unity-plugin#21]
Some rewarded ads doesn't have a close button (I have seen this with AppLovin ads where the ad video just stops without any button, iOS & Android )...  with AdColony when the ad finish I just get a black screen (iOS)... I'm using version 2.8.1

**Comment by nickreffitt** [comment]
Hi @pescode, as mentioned in another ticket, we've made big updates to the plugin, could you try out our latest release to see if this issue goes away?

I'll close this ticket for now, but please reopen if you come across the issue again.

All the best

Nick
