### ISSUE TITLE
VIDEO on iOS, REWARD_AD on Android

### ISSUE THREAD

**Issue by pescode** [tapdaq/unity-plugin#22]
On Android OnAdFinished(TDAdEvent e) returns "REWARD_AD" but on iOS OnAdFinished(TDAdEvent e) returns "VIDEO"... is this behaviour normal? 
I've seen a similar issue here  https://github.com/tapdaq/unity-plugin/issues/8
version 2.8.1

**Comment by nickreffitt** [comment]
Hi @pescode we've made a major change to the iOS part of our Unity plugin, could you try the latest release and let me know how you get on?

You can grab the latest release here https://github.com/tapdaq/unity-plugin/archive/master.zip

I'll close this ticket off for now, but if you have any issues, please reopen this ticket.

Thanks for your patience.

Nick

**Comment by pescode** [comment]
Cool! I'll take a look
