### ISSUE TITLE
No reward videos with 2.0.8 & 2.0.9

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#24]
Hi,

I've updated to the latest plug-in yesterday and no reward videos were showing.
Issues:
- OnAdAvailable rarely called for reward ads
- When it's called ShowRewardVideo did not work, I couldn't see one ad with that version.

Today I've downgraded (all tested within 5 minutes, no other changes except SDK) and tested again,
Results:
- 2.0.9 with iOS 3.0.1 => not working
- 2.0.9 with iOS 2.9.1 => not working
- 2.0.7 with iOS 2.8.1 => working fine (of course with the bugs I've reported previously)

Best.
E.

**Comment by nekenPL** [comment]
Same problem here

**Comment by nekenPL** [comment]
@EarlTapdaq @nickreffitt 
Can You help here?

**Comment by PixelEnvision** [comment]
Any ETA for a new build?

**Comment by nickreffitt** [comment]
Hey @PixelEnvision 

We're just completing a testing phase of the rewarded ads in the Unity plugin, I'll let you know when it's ready, if all things go well, we should have a release out in the next few hours.

All the best

Nick

**Comment by PixelEnvision** [comment]
Hi @nickreffitt that's great news! Thanks for the prompt reply. :)

Best,
E.

**Comment by nickreffitt** [comment]
Hi @PixelEnvision unfortunately we are not able to get a release out today as we are still running into issues with the Rewarded Video ad unit. As soon as we have a stable build ready, I will let you know. 

All the best
Nick

**Comment by PixelEnvision** [comment]
Hi @nickreffitt not a problem, I know coding is not an exact science. :) Thanks for the update!

**Comment by PixelEnvision** [comment]
Hello @nickreffitt any updates?

**Comment by nickreffitt** [comment]
Hi @PixelEnvision & @nekenPL, we have released a new version of the unity plugin, this will resolve the issues you're having with rewarded video

You can grab the latest plugin here https://github.com/tapdaq/unity-plugin/archive/master.zip

Please delete the previous version of the plugin from your project

Let me know if you have any further issues

All the best

Nick
