### ISSUE TITLE
Duplicate Symbol in Xcode

### ISSUE THREAD

**Issue by Entity3Ltd** [tapdaq/unity-plugin#25]
Hi,
I am trying to Archive in Xcode and received the following duplicate symbol errors.
Any ideas why his maybe?

There are lots of them.
Thanks

duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._ratingCount in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_CLASS_$_TDMUAPortrait in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_METACLASS_$_TDMUAPortrait in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._infoButton in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._adClickButton in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._closeButton in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._appIcon in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._appName in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._mainAd in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._star5 in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._star4 in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._star3 in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._star2 in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _OBJC_IVAR_$_TDMUAPortrait._star1 in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/TDMUAPortrait-C2695A3E09504489.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(TDMUAPortrait.o)
duplicate symbol _debugLines in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_CLASS_$_AdNetworkDebugViewController in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_METACLASS_$_AdNetworkDebugViewController in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._navigationItem in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._usingAdapterLabel in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._versionLabel in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._initialisedLabel in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._credentialsDownloadedLabel in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._adNetwork in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._refresh in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._debug in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._adType in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._usingAdapterImage in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._initialisedImage in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._credentialsDownloadedImage in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._showAd in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkDebugViewController._fetchAd in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkDebugViewController-6F8588756F6FB6A0.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkDebugViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkTableViewController.adNetworkArray in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkTableViewController-7431970A1BA08293.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkTableViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkTableViewController._adNetworkTableView in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkTableViewController-7431970A1BA08293.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkTableViewController.o)
duplicate symbol _OBJC_CLASS_$_AdNetworkTableViewController in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkTableViewController-7431970A1BA08293.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkTableViewController.o)
duplicate symbol _OBJC_METACLASS_$_AdNetworkTableViewController in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkTableViewController-7431970A1BA08293.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkTableViewController.o)
duplicate symbol _OBJC_IVAR_$_AdNetworkTableViewController._adNetworkSelected in:
    /Users/Brad/Library/Developer/Xcode/DerivedData/Unity-iPhone-exvspeyyiteyfsenesbjpcirxddx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/AdNetworkTableViewController-7431970A1BA08293.o
    /Users/Brad/Documents/Unity Games/Smash Out/Xcode/SmashOutHeyZap/Frameworks/Plugins/IOS/Tapdaq.framework/Tapdaq(AdNetworkTableViewController.o)

**Comment by nickreffitt** [comment]
Hi @Entity3Ltd, we have released a new version of the unity plugin, this will resolve your issue with the duplicate symbol errors.

You can grab the latest plugin here https://github.com/tapdaq/unity-plugin/archive/master.zip

Please delete the previous version of the plugin from your project.

Let me know if you have any further issues.

All the best

Nick
