### ISSUE TITLE
Small problem with 3.0.0

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#27]
Hi,

Thanks for the update, change log looks great and I'm testing this now.

Upon importing unity package I'm getting following error logged:

"Assets/Plugins/UnityPurchasing/Editor/IAPButtonEditor.cs(37,40): error CS0118: `Editor' is a `namespace' but a `type' was expected"

I think something in your code causes that with Unity IAP (latest version available)

Best,
E.

**Comment by PixelEnvision** [comment]
Follow-up,

For a quick fix I've deleted the script as I won't need it. But multiple other other scripts ended up with the same error. Few samples:

Assets/EasyTouchBundle/EasyTouch/Plugins/Editor/EasyTouchTriggerInspector.cs(13,42): error CS0118: `Editor' is a `namespace' but a `type' was expected

Assets/LeanLocalization/Editor/LeanLocalization_Editor.cs(8,48): error CS0118: `Editor' is a `namespace' but a `type' was expected

Best,
E.

**Comment by nickreffitt** [comment]
Thanks for letting us know about this, i'll chat to our Unity team tomorrow about this issue first thing to see if there's something leaking in our code having a knock-on effect to other scripts.

I'll keep you posted.

All the best

Nick

**Comment by PixelEnvision** [comment]
You're welcome & thank you...

If that helps, that seems to be caused by the editor code in Plugins/Editor/iOS/Xcode where they define "namespace Editor.iOS.Xcode"

Best,
E.

**Comment by nickreffitt** [comment]
Hey @PixelEnvision we've got a release out that should resolve your issue, could you let me know how you get on with this one? https://github.com/tapdaq/unity-plugin/archive/master.zip

Cheers

Nick

**Comment by PixelEnvision** [comment]
Hi @nickreffitt I've just tested it and I can confirm that's not an issue anymore. Plugin is much more easier to work with now, nice work. :)

I've ended up with an null exception but I'm not sure if that's my code or not yet. I'll create new issue shortly if that's from the plugin...
