### ISSUE TITLE
3.0.1 OnAdFinished Triggered early

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#28]
Hello again, so far everything going great with the new build. But I've just noticed following issue:

OnAdFinished called right after OnAdStarted, while the reward video ad is still playing.

Best,
E.

**Comment by nickreffitt** [comment]
Hi @PixelEnvision 

We've made several improvements to both the plugin and the docs regarding Unity callbacks.

Here's a full list of the callbacks docs: https://tapdaq.com/docs/unity-plugin/Advanced 

Let me know if the latest plugin you are testing resolves this issue.

All the best,

Nick
