### ISSUE TITLE
3.0.1 AppLovin SDK key issue?

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#29]
I'm not sure if that's a bug or it's simply not setup at the Appsolute's user panel, so here it is anyway:

[AppLovinSdk] USER [ConnectionUtils] SDK key "randomkeyhere" is rejected by AppLovin. Please make sure the SDK key is correct.

**Comment by nickreffitt** [comment]
Hi @PixelEnvision 

This is an issue with the dashboard settings in David's account, could you ask David to change the key, then you should be able to load AppLovin ads

All the best

Nick

**Comment by PixelEnvision** [comment]
@nickreffitt I will let him know, thank you. Btw, I'm currently uploading our game update to the app store, so far it's going good. :)

**Comment by PixelEnvision** [comment]
@nickreffitt David checked the keys and everything looks correct. But he mentions there are two Applovin keys, api & repot keys.

The logged key is matching the report key, instead of the api one. So, he thinks you might be pulling/checking the wrong one?

I'm not posting the keys here but let me or David know if you need them.

Best,
E.

**Comment by nickreffitt** [comment]
Hey @PixelEnvision this seems strange, could you let me know which app you're integrating, then we can check the settings

All the best

Nick

**Comment by PixelEnvision** [comment]
Hi @nickreffitt, it's kubic. Hints tag used for reward videos. Other providers (vungle, unity ads) seems to be working fine.

**Comment by nickreffitt** [comment]
Hi @PixelEnvision we're struggling to replicate this issue our end, we think the keys may have been changed, could you test this again once more to verify?

Thanks

Nick

**Comment by PixelEnvision** [comment]
Sure, I'll test and post the results as soon as I can... :)

**Comment by PixelEnvision** [comment]
@nickreffitt I've just tested it and I can confirm it's no longer logs the error. AFAIK at one point David refreshed the Applovin link on the dashboard, that might have fixed the problem before you tested it...

Thanks for your help!

Best,
E.

**Comment by nickreffitt** [comment]
Great stuff, let me know if you have any further issues, I'll close this ticket off in the meantime

All the best

Nick
