### ISSUE TITLE
SDK v3.0

### ISSUE THREAD

**Issue by ayublin** [tapdaq/unity-plugin#3]
Hello, shouldn't this get updated to SDK version 3.0 as well? Thanks.

**Comment by nickreffitt** [comment]
Hey @ayublin thanks for the note

We're just in final stages of launching our Unity plugin, I'll keep this ticket open until we've released it so you are informed.

Let me know if you have any other questions

**Comment by agarwalmukund** [comment]
Hey @ayublin 
The new version is out.
Please let us know if there are any issues.
Thank you,
Mukund
