### ISSUE TITLE
Quickstart guide fix

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#30]
Hi, there is a small correction needed for "Submitting your app to Apple" section of the quick-start guide:

NSCalendarUsageDescription => NSCalendarsUsageDescription

**Comment by nickreffitt** [comment]
Fantastic, thanks @PixelEnvision - you are a superstar

**Comment by nickreffitt** [comment]
Hi @PixelEnvision - just a follow-up here to say this has now been fixed in the Quickstart guide

If you have any other feedback on the docs, we would love to hear it.

All the best

Nick
