### ISSUE TITLE
Unity Ads?

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#33]
Hi again,

You might already aware of that but I wanted to open an issue anyway. We can't get Unity Ads to show even if it's the only provider as David turned Applovin & Vungle off in the dashboard.

It looks like SDK doesn't downloads Unity Ads videos as they are never ready to play. Any thoughts?

Best,
E.

**Comment by PixelEnvision** [comment]
I'm not sure how but that issue seems to be fixed now. :)

**Comment by nickreffitt** [comment]
Hi @PixelEnvision we have been able to replicate this issue our end, and we have put out a small fix for this, please download the latest SDK from https://github.com/tapdaq/unity-plugin/archive/master.zip

Let me know if you have any issues

**Comment by PixelEnvision** [comment]
Thank you @nickreffitt I've just updated the SDK & re-submitted the binary. It looks ok so far...

**Comment by PixelEnvision** [comment]
Final update: David also tested it individually with every ad network and all 👍, thanks for the help!

**Comment by nickreffitt** [comment]
Hi @PixelEnvision thanks so much for checking this over, you've been a fantastic help.
