### ISSUE TITLE
TapdaqConfigLoaded not called 3.2.0

### ISSUE THREAD

**Issue by erebar** [tapdaq/unity-plugin#34]
TapdaqConfigLoaded is never called in the latest version of the unity plugin. The same code works in version 3.1.0 and it shows ads.

Also when I check the test scene its messed up. Attaching screenshot:

http://imgur.com/RqLaAhT

**Tested on Unity 5.5.1f1 and only on iOS.**

**Comment by rdominic** [comment]
Hi erebar,

We're aware of that issue on iOS, we'll be pushing an update soon - should be tomorrow, can I confirm that's the platform you're having the issue on?

We'll take a look at the sample app test scene and fix that with the update.

Thanks for getting in touch,
Dominic

**Comment by erebar** [comment]
Hi Dominic, yes its on iOS.

**Comment by rdominic** [comment]
Hi Erebar, 

We've just pushed a release 3.3.0. The native ad sample app should now have the scripts linked up correctly and TapdaqConfigLoaded called correctly on boot.

Thanks,
Dominic
