### ISSUE TITLE
3.5.0 Android problem

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#35]
Hello,

I'm working on android update of our game and I've updated sdk to 3.5.0 today. Currently it's not working with the following issues:

1. Build fails with the following error: AndroidManifest.xml:4: error: Error: No resource found that matches the given name (at 'banner' with value '@drawable/app_banner').

I've fixed that by removing app_banner declaration from manifest.

2. No ads are showing, I think that is the cause:
02-16 17:56:21.363: I/TAPDAQ_INFO(5792): TAPDAQ has not been initialised
02-16 17:56:21.383: I/dalvikvm(5792): Could not find method android.content.res.Configuration.getLocales, referenced from method com.tapdaq.sdk.helpers.TDDeviceInfo.getCountry

Any comments?

Best regards,
E.

**Comment by nickreffitt** [comment]
Hi @PixelEnvision 

Could I ask what minimum Android API version your app is set to? 

The Tapdaq SDK supports Android API levels 9+, although if using the Facebook Audience Network Mediation Adapter, it only supports 11+

All the best

Nick

**Comment by PixelEnvision** [comment]
Hi @nickreffitt 

It's set to API Level 11, building with Unity 5.4.4p3

We're using reward videos with Vungle, Unity & Applovin

**Comment by PixelEnvision** [comment]
Another update,

I've found this in the logs if that helps:
02-16 18:17:49.690: I/Unity(8020): _didFailToLoad {"message":"No Network available","tag":"hints","adType":"REWARD_AD"}

Also Unity crashes after build, when installing apk to the device. I'm not sure if that's Tapdaq related but I wanted to let you know...

**Comment by nickreffitt** [comment]
Do you have ProGuard enabled on your android build? I think it's removing Android API methods

**Comment by PixelEnvision** [comment]
Thanks for the reply, no I'm not using ProGuard...

But I was using IL2CPP, I've switched back to mono and it seems to get rid of those errors but still no ads are showing. Now I'm receiving those:

02-16 19:11:08.771: I/TAPDAQ_INFO(12194): Initialised Tapdaq Version: unity-android-sdk_4.4.1
02-16 19:11:09.051: D/TAPDAQDEBUG(12194): The response is: 400
02-16 19:11:09.051: E/TAPDAQ_ERROR(12194): Credentials Error
02-16 19:11:09.051: D/TAPDAQDEBUG(12194): ERROR
02-16 19:11:09.081: E/TAPDAQ_ERROR(12194): Credentials Error
02-16 19:11:09.081: D/TAPDAQDEBUG(12194): ERROR

**Comment by nickreffitt** [comment]
Hi @PixelEnvision 

Would you be able to send me an email to support@tapdaq.com with the name of the app and the App ID you are using?

Thanks

**Comment by PixelEnvision** [comment]
Sent :)

**Comment by PixelEnvision** [comment]
Hi @nickreffitt 

Credentials were correct, apparently ad networks were not enabled for Android at the time. David confirmed setting them up today but I'm still not seeing any ads with the following logs as before:

02-17 14:17:24.692: D/TAPDAQDEBUG(24386): The response is: 400
02-17 14:17:24.802: E/TAPDAQ_ERROR(24386): Credentials Error
02-17 14:17:24.812: D/TAPDAQDEBUG(24386): ERROR
02-17 14:17:24.882: E/TAPDAQ_ERROR(24386): Credentials Error
02-17 14:17:24.882: D/TAPDAQDEBUG(24386): ERROR

Any ideas?

**Comment by nickreffitt** [comment]
Hi @PixelEnvision 

We've just pushed a new release for the Unity plugin, could you give this a try and let me know how you get on?

https://tapdaq.com/docs

All the best

Nick
