### ISSUE TITLE
3.6.0 Android Issues

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#36]
I've just upgraded my project to 3.6.0 and I still cannot see any reward videos. List of current issues:

1. Build fails due to following application declaration in AndroidManifest.xml, removing it allows build to proceed without any errors:
android:banner="@drawable/app_banner"

2. OnTapdaqConfigLoaded(string message) callback causes compile error: "error CS0123: A method or delegate `newAds.OnTapdaqConfigLoaded(string)' parameters do not match delegate `System.Action()' parameters"
I can fix that by removing (string message) and using just () for the callback function.

3. When build and run on the device I'm not seeing any Initialization logs on the first run. If I pause & resume the game following log is posted on each time:

02-18 11:57:45.590: I/TAPDAQ_INFO(25668): Initialised Tapdaq Version: unity-android-sdk_4.4.1
02-18 11:57:46.061: D/TAPDAQDEBUG(25668): The response is: 400
02-18 11:57:46.141: E/TAPDAQ_ERROR(25668): Credentials Error
02-18 11:57:46.141: D/TAPDAQDEBUG(25668): ERROR
02-18 11:57:46.251: E/TAPDAQ_ERROR(25668): Credentials Error
02-18 11:57:46.251: D/TAPDAQDEBUG(25668): ERROR

**Comment by PixelEnvision** [comment]
I'm also seeing those in logcat on the app launch if that helps.

02-18 12:16:13.871: I/dalvikvm(27998): Could not find method android.content.res.Configuration.getLocales, referenced from method com.tapdaq.sdk.helpers.TDDeviceInfo.getCountry
02-18 12:16:15.333: I/dalvikvm(27998): Could not find method android.content.Context.checkSelfPermission, referenced from method com.tapdaq.sdk.storage.FileStorage.getFile
02-18 12:16:15.343: I/dalvikvm(27998): Could not find method android.content.Context.checkSelfPermission, referenced from method com.tapdaq.sdk.storage.FileStorage.getPath

**Comment by PixelEnvision** [comment]
On another note, just to make sure it's not something in my project I've created a new Unity project with just the TapDaq plugin imported. Attached a basic init script to the camera of an empty scene. All android settings at defaults just with my own app ID entered in tapdaq settings.

Result is the same as above.

**Comment by PixelEnvision** [comment]
I think this a permission issue? I was playing with emulators to test the dummy project.

It seems to be working with recent Android (7.7.1) after I allow a permission pop-up at the app launch.

But it's not working with my test device Galaxy Tab 3, with Android 4.4.2. It's API Level 19 which should be supported, right?

Best,
E.

**Comment by nickreffitt** [comment]
Hi @PixelEnvision 

Thanks very much for your feedback.

Our initial findings suggest that 1. & 3. are related to Manifest problems.

2. You are correct, we omitted the parameter from the `OnTapdaqConfigLoaded()` method, we will update the docs right away.

We're going to continue to look into the authentication issue you are having, as we've not been able to replicate it our end.

Thanks again and apologies you are hitting issues again, we really appreciate your patience.

Nick

**Comment by PixelEnvision** [comment]
Hi @nickreffitt you're welcome and thank you for your prompt reply. It's not a problem with the issues, there are no time constraints for this one. :)

I should add although I'm seeing ads with Android 7 (emulator), there were two errors:
* It couldn't load & show Applovin ads, I'm not sure if that's the plugin or some setup problem at the David's account panel.
* Also there were another error log complaining about webview (I don't have the exact error msg right now), but that might be an emulator issue. But I did saw few Vungle ads but no Unity ads.

But same apk is not working with my test device, I think you'll need pre Android 6.0 era device to replicate the issue...

Have a nice weekend!

Best regards,
Erdener

**Comment by nickreffitt** [comment]
Hi @PixelEnvision 

We shall check on David's account shortly and let you know if there's a setup issue, are you testing Rewarded Video? 

We do some more testing on Android 6.0, that version is supported so we will double check. 

Let me know if you come across any more issues, your feedback is truly superb!

All the best 

Nick

**Comment by PixelEnvision** [comment]
Yes, we're using same setup as iOS, three providers all for Rewarded Videos: Applovin, Vungle & Unity.

I think you'll need 4.x device to test & possibly replicate my results as Android moved to new permission system with 6+

Thanks, I'm glad to be helpful. :)

**Comment by asancio** [comment]
Hello, 
1 is still a problem, we had to remove (android:banner="@drawable/app_banner") from the manifest to build on Unity.

Andrea

**Comment by PixelEnvision** [comment]
3.7.0 seem to resolve most of those problems except I had to remove android:banner="@drawable/app_banner" from manifest as reported above.

**Comment by rdominic** [comment]
Hi, the manifest is currently undergoing some major reconfiguring and as such wasn't ready for this release. It will be there in the next release along with improvements to our file structure for Android Libraries/Manifests which will cause less issues and conflicts.

For now please continue to just remove the `android:banner="@drawable/app_banner"` code.

Dominic
