### ISSUE TITLE
Invalid Application ID crash

### ISSUE THREAD

**Issue by erebar** [tapdaq/unity-plugin#4]
Hi, since the new sdk was released I'm getting "Invalid Application ID crash" on my new apps that use Tapdaq. On native ios apps the problem was solved by using the latest sdk, but with unity the apps keep crashing. What should I do?
![tapdaqcrash](https://cloud.githubusercontent.com/assets/5253547/20861484/71d1d662-b95f-11e6-9f11-e545fac4b948.jpg)

**Comment by agarwalmukund** [comment]
Hey @erebar 

We are about to release the updated Unity SDK really soon. This will resolve this issue as it will add support for the new appID format.
We will let you know as soon as it's released.
Sorry for the inconvenience.

Thank you,
Mukund

**Comment by erebar** [comment]
Ok. Thanks.

**Comment by agarwalmukund** [comment]
Hey @erebar,
The new version is out now which should resolve this issue.
Kind regards,
Mukund
