### ISSUE TITLE
4.2.0 throwing a lot of exception when adapter missing

### ISSUE THREAD

**Issue by ayublin** [tapdaq/unity-plugin#43]
Hello,

As it's up to us what networks we wish to include into the project, I think tapdaq shouldn't throw exception as it could fill up the error tracking tool such as fabric, here is an example:

![image](https://cloud.githubusercontent.com/assets/1355215/24065975/7d9a852c-0ba1-11e7-8b98-b2320b164245.png)

Thanks!

**Comment by rdominic** [comment]
Hi,

Yeah, that doesn't look good. We'll look at hiding that.

Thanks,
Dominic

**Comment by nickreffitt** [comment]
Hi @ayublin 

Thanks for your patience whilst we work through the issues you are experiencing. 

We have released a new version of our unity plugin which will resolve both ticket #43 and #47 for you. Could you try the latest version and let me know how you get on?

All the best,

Nick

**Comment by ayublin** [comment]
Hi @nickreffitt 

Many thanks! Sure, will do.
