### ISSUE TITLE
[iOS] Empty tag in TDAdEvent - AdDidDisplay callback

### ISSUE THREAD

**Issue by wkluczniak** [tapdaq/unity-plugin#44]
I'm getting empty tag on didDisplay callback. Here's a callback implementation and resulting log

![zrzut ekranu 2017-03-19 o 21 03 14](https://cloud.githubusercontent.com/assets/19508961/24084294/c7d5373a-0ce7-11e7-8525-859c1058dffd.png)
![zrzut ekranu 2017-03-19 o 21 02 34](https://cloud.githubusercontent.com/assets/19508961/24084295/ca090c48-0ce7-11e7-84e0-eb211ef01747.png)

**Comment by nickreffitt** [comment]
Hi @wkluczniak 

We're looking at adding in placement tags to didDisplay, willDisplay, didClick and didClose in a future release, could I ask what your use-case is for needing the placement tag on that callback?

All the best,

Nick

**Comment by nickreffitt** [comment]
Hey @wkluczniak 

I'm pleased to say out latest Unity plugin now includes placement tags to each callback!

Could you give it a try and let us know how you get on?

Feel free to reach out on support@tapdaq.com 

Cheers,

Nick
