### ISSUE TITLE
Android Chartboost plugin missing

### ISSUE THREAD

**Issue by wkluczniak** [tapdaq/unity-plugin#45]
.unitypackage file for Chartboost only contains iOS files, so Android throws exceptions:
![ex](https://cloud.githubusercontent.com/assets/19508961/24220828/2fb4be6e-0f4c-11e7-9f87-9dfbbbea5a3c.jpg)

**Comment by nickreffitt** [comment]
Hi @wkluczniak 

We're taking a look at this our side, and pushing out a fix to remove this log message.

The log is a false positive - you should be able to display ads from Chartboost, are you able to confirm that?

All the best,

Nick

**Comment by nickreffitt** [comment]
Hi @wkluczniak 

We've made an update to the SDK whereby this log will not be displayed, we can confirm that this was a false-positive on our end, apologies about that.

Could you try the latest SDK and let me know how you get on?

All the best,

Nick

**Comment by wkluczniak** [comment]
Latest version seems to be all good 👍
