### ISSUE TITLE
Can't find IsBannerReady

### ISSUE THREAD

**Issue by mtoanhcm** [tapdaq/unity-plugin#46]
I follow your guild about banner and I can't find IsBannerReady( ), please add it

**Comment by nickreffitt** [comment]
Hi @mtoanhcm, 

Sorry you are having issues here, we're taking a look at your issue. 

I can see that iOS supports this method call, but Android does not. Am I correct in saying you are testing with builds to Android?

Cheers,

Nick

**Comment by mtoanhcm** [comment]
Thanks for your answer, Im using tapdaq plugin for android build.

**Comment by nickreffitt** [comment]
Hi @mtoanhcm 

Great news, we've added in the method call for IsBannerReady()

Could you try the latest version of our plugin and let me know how you get on?

All the best,

Nick
