### ISSUE TITLE
Frequent Crashing

### ISSUE THREAD

**Issue by ayublin** [tapdaq/unity-plugin#47]
Hello, we're getting a quite bad crash case:

https://pastebin.com/egL3vDvG

![image](https://cloud.githubusercontent.com/assets/1355215/24368046/2ffaddf8-1349-11e7-88ef-3d274608911d.png)

More than 500 occurrences so far, anyway we're using 4.0.0 as I assume the latest version still has this issue https://github.com/tapdaq/unity-plugin/issues/43.

**Comment by ayublin** [comment]
Another one:

https://pastebin.com/kukLWr6r

![image](https://cloud.githubusercontent.com/assets/1355215/24368205/c4b73aa4-1349-11e7-8f4e-f7d2856c0442.png)

Thanks.

**Comment by nickreffitt** [comment]
Hi @ayublin ,

I'm very sorry about this, we're taking a look at the issue and will get back to you ASAP.

Thanks for your patience

Nick

**Comment by rdominic** [comment]
Hi @ayublin 

Can you take a look over your integration? Those logs don't match UnityPlugin v4.0.0.
TapdaqUnity activity no longer needs to be included in the manifest, if you're updating from a version before 4.0.0 then I recommend removing all of tapdaq files and importing them again, this version structured the android files much better, so the manifest's automatically merge. It should be easier to keep track of Tapdaq files with this version onwards.

Thanks,
Dominic

**Comment by ayublin** [comment]
@rdominic how do I check my current tapdaq version? there is a possibility that in fact I was wrong and actually using v3.7.0, also with our current integration we can show the cross promo interstitial just fine.

**Comment by rdominic** [comment]
You can see android sdk version contained in the plugin in the logs
`I/TAPDAQ_INFO: Initialised Tapdaq Version: unity-android-sdk_4.10.1`

Unity Plugin 4.0.0 should contain android sdk 4.7.1

We're looking at surfacing the Unity Plugin version, but currently it's not stated anywhere, the files you should have shown below or you can see them in the samples folder https://github.com/tapdaq/unity-plugin

<img width="421" alt="screen shot 2017-03-28 at 16 07 36" src="https://cloud.githubusercontent.com/assets/5871110/24412590/c7f511a0-13d0-11e7-8551-24e242cd5ee7.png">

**Comment by ayublin** [comment]
Alright, I have confirmed that I am using version 3.7.0, so my integration should be fine, this is the latest commit related to updating tapdaq.

![image](https://cloud.githubusercontent.com/assets/1355215/24413951/2716cd28-1407-11e7-9db4-04209501bcd9.png)

So are the issues I am seeing was known and fixed on the newer version?

**Comment by rdominic** [comment]
We've not seen these logs yet, others have been working ok, so I'm wondering if there's an integration issue still. Is the TapdaqUnity activity stated in the manifest correctly?

Should look like this:
https://github.com/tapdaq/unity-plugin/blob/master/Samples/MediationSample/Assets/Plugins/Android/AndroidManifest.xml

The second log looks like you need to include the INTERNET permission which should also be in that manifest file. 

I highly recommend using v4.0.0 or newer as we've resolved a lot of the manifest issues now.

**Comment by ayublin** [comment]
We have added that permission of course, and yes we have stated the TapdaqUnity activity correctly. Also I think you are referring to the wrong manifest, that is for version 4.0.0.

Well even though others haven't seen them, doesn't mean it's not existent, I hope you will be willing to check into those error stack trace anyway. But you can just assume there is something wrong with my integration :)

**Comment by nickreffitt** [comment]
Hi @ayublin 

My apologies here, I appreciate it's frustrating for you to have this issue, we're determined to get your problem solved as quickly as possible.

Would you mind giving our latest SDK a try? We have dived into the stack trace you provided us, and we're confident that the problem your experiencing was fixed in the latest release.

I'm more than happy to jump on a Skype call tomorrow if you prefer to talk things over.

All the best,

Nick

**Comment by ayublin** [comment]
Hi @nickreffitt 

So those issues indeed can occur on older version?

I did wish to try the latest version, but this issue drawn me back https://github.com/tapdaq/unity-plugin/issues/43 and I don't see them resolved in the 4.2.1 changelogs.

Thanks for the offer Nick, really appreciate it, but as for now, I don't see the need for a call, thanks anyway!
