### ISSUE TITLE
A method or delegate `GameManager.OnTapdaqConfigLoaded(string)' parameters do not match delegate `System.Action()' parameters

### ISSUE THREAD

**Issue by Entity3Ltd** [tapdaq/unity-plugin#48]
Hi, I am getting the following error in unity by using the below functions described in the wiki.
Can you let me know what I am missing here please, i am 'using Tapdaq;'

A method or delegate `GameManager.OnTapdaqConfigLoaded(string)' parameters do not match delegate `System.Action()' parameters

        private void OnEnable() {
		TDCallbacks.TapdaqConfigLoaded += OnTapdaqConfigLoaded;
	}

	private void OnDisable() {
		TDCallbacks.TapdaqConfigLoaded -= OnTapdaqConfigLoaded;
	}

**Comment by rdominic** [comment]
Hi @Entity3Ltd 

Sorry, that String parameter is no longer required, I've updated the doc to reflect this 
https://github.com/tapdaq/unity-plugin/wiki/Advanced

Your method should now look like this:
```
private void OnEnable () {
    TDCallbacks.TapdaqConfigLoaded += OnTapdaqConfigLoaded;
}

private void OnTapdaqConfigLoaded() {
}
```

Dominic

**Comment by Entity3Ltd** [comment]
Yep thats fine, thanks for the quick response
