### ISSUE TITLE
Crash on Launch iOS/Xcode

### ISSUE THREAD

**Issue by Entity3Ltd** [tapdaq/unity-plugin#5]
After the build completes and Xcode runs on the device it crashes out with the following error.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'

This is being cause by AdManager.Init(); in void Start()
If this is commented out then the app runs fine.

Please advise

**Comment by agarwalmukund** [comment]
Hey @Entity3Ltd 
Thank you for reaching out.
Can you please confirm if your test device doesn't contain a SIM card?
We have come across this error this week and have narrowed down it to a 'No SIM' scenario issue and
we will be releasing a fix soon.
If the test device does contain a SIM card then please send us a copy/link of the full debug log and we will investigate further.
Kind regards,
Mukund

**Comment by Entity3Ltd** [comment]
Yes thats a good shout there is no sim card. I will try a sim.

Does this mean it will not work on a device such as an ipad which can not take a sim? or only if the no sim message shows?

Thanks

**Comment by agarwalmukund** [comment]
Hey @Entity3Ltd 
Thank you for confirming.
It works fine on iPad and iPod Touch.
Only iPhone with 'No SIM' status are facing this issue.

Should have a new version out soon. Will keep you updated.

Kind regards,
Mukund

**Comment by agarwalmukund** [comment]
Hey @Entity3Ltd 
The new version is out now.
Please let us know if there are any issues.
Kind regards,
Mukund
