### ISSUE TITLE
Banner off center - Portrait

### ISSUE THREAD

**Issue by Entity3Ltd** [tapdaq/unity-plugin#50]
Hi,A few times now I have seen a banner which has been displayed off center to the right. The game is iOS (iPhone 6) and is in portrait orientation. Any Suggestions Thanks

Please email me for a screenshot / image if needed. Thanks

**Comment by Entity3Ltd** [comment]
This has not happened since. Do you want to look into this or should I just close this issue?
Thanks

**Comment by nickreffitt** [comment]
Hey @Entity3Ltd 

We're struggling to replicate this ourselves, if it comes up again please let us know, but for the meantime, we will close off this ticket.

Thanks

Nick
