### ISSUE TITLE
Temp\StagingArea\android-libraries\Tapdaq' is missing AndroidManifest.xml file.

### ISSUE THREAD

**Issue by minhit1805** [tapdaq/unity-plugin#51]
Hello, current i'm using an old version tabdaq, then install new version but i get this error, 
StagingArea\android-libraries\Tapdaq' is missing AndroidManifest.xml file.
someone can tell me some idea to fix this problem? thanks.

**Comment by nickreffitt** [comment]
Hi @minhit1805, 

Would you be able to update to the latest Unity plugin and give that a try? We've made a lot of improvements with regards to android builds.

Feel free to reach out to support@tapdaq.com if you have any further issues.

All the best,

Nick
