### ISSUE TITLE
Interstitial Ad not Loading

### ISSUE THREAD

**Issue by AasiqSA** [tapdaq/unity-plugin#53]
Hi, I am using tapdaq vesion in unity 5.5.2f personal edition.
I am not using any tags for both interstitial and reward ads. that is, I am loading and showing using
Admanager.LoadInterstitial();
Admanager.ShowInterstitial();

Admanager. LoadRewardedVideo();
Admanager.ShowRewardVideo(); 

The reward ad is working fine, But the interstitial is not loading.
It shows "could not find registered placement for tag:default. Adunit: static_interstitial. Have you registered the tag correctly" in xcode log.
Could you help me with this?

**Comment by AasiqSA** [comment]
Update:
I have even tested loading interstitial with placement tags.
No change...

**Comment by alagatar** [comment]
Hi, 
Try updating to new version and check your dashboard for confirmation.

**Comment by nickreffitt** [comment]
Hey @AasiqSA 

You will need to register the tag "default" in the Tapdaq Settings, to do this, please see step 1 in each of our ad unit guides, for example: https://tapdaq.com/docs/unity-plugin/Interstitial#1-register-a-placement-tag 

If you have any further questions, please reach out to support@tapdaq.com and we can respond much faster for you.

All the best,

Nick
