### ISSUE TITLE
Crash on Reward Video End

### ISSUE THREAD

**Issue by Entity3Ltd** [tapdaq/unity-plugin#6]
Hi, I am facing an issue with the game crashing out after a reward video finishes playing. I am unsure which network is being used for the video, prehaps Unity Ads.

I also have an issue with reward videos from Vungle, once the video is finished I can not click the 'X' to close the advert. 

Any suggestions?

Thanks

**Comment by agarwalmukund** [comment]
Hey @Entity3Ltd,

Please check the last step regarding 'Build phases' in [Unity Quickstart](https://github.com/tapdaq/unity-plugin/wiki/Quickstart#ios-specific-steps)
This should fix the UnityAds crash issue.

With regards to the Vungle close button, there is an issue where the close button is slightly below the actual close button image. This will be fixed soon and I will let you know once its released.

Thank you,
Mukund

**Comment by Entity3Ltd** [comment]
Thanks must have missed those, sorry.

However with them added I no get the following error messages on building

'TDMUAPortrait.h' file not found
'AdNetworkDebugViewController.h' file not found

**Comment by agarwalmukund** [comment]
Hey @Entity3Ltd,

No, thats ok. We did update that part yesterday only. So, you probably used the wiki just before that.
Those errors regarding *.h files shouldn't be there if the 'Compile Sources' section contains the right *.m files. 
If that section looks correct please send me your project via support@tapdaq.com and I will investigate it further.
Thank you,
Mukund

**Comment by Entity3Ltd** [comment]
Ok, So I added the 3 x .h files into the 'Compile Sources' too, this then builds fine and the crash on video completion has gone. Thanks

Please let me know when the Vungle Ad close issue is resolved.

**Comment by agarwalmukund** [comment]
Hi @Entity3Ltd,

The Vungle ad close issue has been fixed in the latest release.

Thank you,
Mukund
