### ISSUE TITLE
Interstitials not showing

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#7]
Hi,

Thank you for your email reply yesterday. New build & updated quick start guide solved most of the problems with video ads (except the Vungle close button bug reported here) but I’m still not seeing any interstitials. 

* I’m calling AdManager.Init () at Start()
* Then waiting for the OnAdAvailable listener to confirm an interstitial is available.
* Then I call it using the AdManager.ShowInterstitial with 3 seconds delay.

Do we need to setup/define something on tapdaq.com account first?

Thank you!

**Comment by Entity3Ltd** [comment]
I am also experiencing no Interstital ads showing

**Comment by agarwalmukund** [comment]
Hey @PixelEnvision,

I logged in your Tapdaq account and have enabled AppLovin for interstitial. Other networks which you have enabled only do video ad type. That should resolve your issue assuming your AppLoving dashboard is also configured correctly.


Hey @Entity3Ltd,

I logged in your Tapdaq account as well and don't see any ID entered for AdMob static interstitial ad type. Please copy that ID over from your AdMob account and that should resolve your issue as well.

Thank you,
Mukund

**Comment by Entity3Ltd** [comment]
@agarwalmukund 
I am using a clients ID's for this project and not my setup. I will check with them.
Thanks

**Comment by PixelEnvision** [comment]
@ Mukund Thank you, I'll check it now...

**Comment by PixelEnvision** [comment]
Apparently issue was tag assignment, so I'm closing this entry...
