### ISSUE TITLE
VIDEO instead of REWARD_AD

### ISSUE THREAD

**Issue by PixelEnvision** [tapdaq/unity-plugin#8]
Hello again,

Here are the details:
* Fist I'm waiting for OnAdAvailable with e.adType == "REWARD_AD"
* When it's confirmed I'm enabling a button to watch it
* When button is pressed it calls AdManager.ShowRewardVideo ("hints");
* We've assigned reward videos to the hints tag and it's set-up as reward video in Tapdaq settings
* When "hints" called OnAdStarted callback logs -- Test Log -- VIDEO: WILL_DISPLAY
* When the video ends OnAdFinished logs -- Test Log -- VIDEO: AD_ENDED

I was expecting REWARD_AD type to start & end instead of VIDEO and the main problem is video is skippable.

Also few times OnAdStarted without actually showing anything.

Thank you... :)

**Comment by agarwalmukund** [comment]
Hey @PixelEnvision,

Just want to confirm that is this issue for iOS or Android platform?

Kind regards,
Mukund

**Comment by PixelEnvision** [comment]
@agarwalmukund it's for iOS

**Comment by agarwalmukund** [comment]
Hey @PixelEnvision,

Thank you for the info. 

- The video skip issue for rewarded is known and I am working on it to fix it for the next release.

- With regards to the "VIDEO: WILL_DISPLAY and AD_ENDED" calls that is intentional as we want to provide a common delegate to notify when a video (normal or rewarded) is played and when it finishes playing. One thing we could do is change the Unity delegate labeling to "VIDEO/REWARDED" instead of just "VIDEO"

When the rewarded video finishes playing it will trigger DID_CLOSE with the reward amount/value.
Please let us know if that's not the case.

- OnAdStarted should only show up when an ad unity is about to be displayed. Please let me know if that is not the case with the latest release.

Thank you,
Mukund

**Comment by PixelEnvision** [comment]
@agarwalmukund thank you for your reply.

Should I see the "DID_CLOSE" with the latest release 2.0.4 (with iOS 2.6.1) or is it scheduled for the next one?

Regarding "VIDEO/REWARDED", for me if there is a "DID_CLOSE" there won't be a much use but on the other hand it might be a good idea to separate those two for future flexibility...

Best regards,
E.

**Comment by PixelEnvision** [comment]
Ah, apparently there is a AdClosed callback that'll return "DID_CLOSE". I'll try that now.

FYI, it's not listed in listeners section of the quick-start guide...

**Comment by agarwalmukund** [comment]
@PixelEnvision sorry for that.
We are still in the process of getting the Unity wiki/SDK properly up to date. :)
Thank you for the patience.

**Comment by PixelEnvision** [comment]
Not a problem, I'll let know how that goes :)

**Comment by PixelEnvision** [comment]
@agarwalmukund So far so good. :)

* When I receive, for example REWARD_AD: VALIDATED:UnityAds NA, I assume that NA would be the  reward amount/value, correct? Do we need to set that in developer console? Also any chance to assign that to a numerical value such as "e.amount"?

* When you disable the skip option for reward videos, would that require a SDK update?

* I did receive few video fails and when it happens error is called right after start callback, i.e:

-- Test Log -- VIDEO: WILL_DISPLAY
newAds:OnAdStarted(TDAdEvent)
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

-- Test Log -- VIDEO: FAILED_TO_DISPLAY
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

**Comment by agarwalmukund** [comment]
Hey @PixelEnvision,

Great to know its coming through!

- Yes, it seems that the reward amount and value are not being relayed to Unity correctly. I will let the Unity team know.
- Yes, the skip fix will require an SDK update, unfortunately.
- I will remove the willDisplayVideo calls in the failed scenario in the next SDK release as well.

Thank you,
Mukund

**Comment by Entity3Ltd** [comment]
What is your expected time frame to fix the Reward video skipping issue? This is quite an important thing for me.

**Comment by agarwalmukund** [comment]
Hey @EntityLtd
The skipping issue fix will be released by end of Monday.
Thank you,
Mukund

**Comment by PixelEnvision** [comment]
@agarwalmukund I see the plugin is updated, is this the one with skipping fix?

**Comment by agarwalmukund** [comment]
Hi @PixelEnvision,

No, that update was just to push the Friday changes (v2.6.1) out correctly.
I am working on the skipping fix now and should be out before the end of today.
Will keep you updated.

Thank you,
Mukund

**Comment by PixelEnvision** [comment]
@agarwalmukund Ah, that's great news. Thanks you!

**Comment by agarwalmukund** [comment]
Hi @PixelEnvision 

We have just released the new version (2.0.6) now.

Thank you,
Mukund
