### ISSUE TITLE
OnAdAvaliable Issue

### ISSUE THREAD

**Issue by Entity3Ltd** [tapdaq/unity-plugin#9]
Hi, I am trying to make a button intractable once a Reward Ad is ready to be shown.
Sometimes this does not complete. You can literately sit in the scene forever and the button will not activate. However if you come out of the scene and go back in sometimes it will activate after a second or two, but then sometimes still not at all.
Below is what I am using in the script.

> using UnityEngine;
> using System.Collections;
> using UnityEngine.SceneManagement;
> using UnityEngine.UI;
> using Tapdaq;
> 
> 	private void OnEnable () {
> 		TDCallbacks.AdAvailable += OnAdAvailable;
> 	}
> 
> 	private void OnDisable () {
> 		TDCallbacks.AdAvailable -= OnAdAvailable;
> 	} 
> 	
> private void OnAdAvailable (TDAdEvent e) {
> 		if (e.adType == "REWARD_AD") {
> 			Button.interactable = true;
> 		}
> 	}

**Comment by nickreffitt** [comment]
Hi @Entity3Ltd - thanks for this, we're going to try and re-create the issue our end then get back to you as soon as we have more info

Thanks for letting us know about the issue, you've been a great help! :) 

Nick

**Comment by erebar** [comment]
Hi, I'm having the same issue. AdAvailable never fires.

**Comment by Entity3Ltd** [comment]
Yes this was on iOS, not sure i mentioned that.
@nickreffitt Have you been able to replicate this issue your end?
Thanks

**Comment by nickreffitt** [comment]
Hi @Entity3Ltd - yes I can confirm we can replicate the issue our end, our team has moved this ticket to first priority, I will get back to you as soon as I have an update from our engineers

All the best

Nick

**Comment by Entity3Ltd** [comment]
@nickreffitt This appears to be 'slightly' fixed in your latest update.
The buttons now activate quite quickly once a reward video is ready. I no longer have to come out of the scene and go back in.

However I have 3 buttons that should activate under the following function. But all buttons do not always activate at once, some activate later.

private void OnAdAvailable (TDAdEvent e) {
		if (e.adType == "REWARD_AD") {
			Button1.GetComponent<Button>().interactable = true;
			Button2.GetComponent<Button>().interactable = true;
			Button3.GetComponent<Button>().interactable = true;
		}
	}

**Comment by nickreffitt** [comment]
Hi @Entity3Ltd @erebar 

We have made major improvements in our ad serving, which should resolve all your issues here

You can grab the latest SDK from the following link: https://github.com/tapdaq/unity-plugin/archive/master.zip

If you continue to have problems, please reopen the ticket and let me know.

Apologies for the delay and thank you for your patience.

All the best

Nick
